### PR TITLE
Modified SplashBuddy to launch over the Login Window

### PR DESCRIPTION
**Pull request by smithjw**
Included some logic in the launch script to determine if the admins deploying SplashBuddy would like SB to launch over the Login Window
Additionally fixed up some spelling errors in the presentation.bundle from my earlier PR 😅

### CODE REVIEW

**Comment by smithjw** [comment]
@Ethenyl Added in a slight change to the Launch Script. Info in the commit. I believe it should still show in the same Pull Request

**Comment by smithjw** [comment]
Was this going to be merged at some point? 😂

**Comment by Ethenyl** [comment]
Hi @smithjw,

Can you rebase on `develop` to prevent history issues? Once it's done I should be able to merge the PR.

Thanks in advance.

**Comment by Ethenyl** [comment]
Hi @smithjw,

Still waiting for your rebase on the actual development branch. Unless you do it, I can't merge this PR.

Thanks.

**Pull request closed without merging**
